name: Terraform Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.14.9
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  # terraform-backend:
  #   name: Backend - Init, Plan, Apply
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: ${{ env.TERRAFORM_VERSION }}

  #     - name: Initialize Backend
  #       run: cd backend && terraform init

  #     - name: Plan Backend
  #       run: cd backend && terraform plan -var-file=dev.tfvars

  #     - name: Apply Backend
  #       run: cd backend && terraform apply -auto-approve -var-file=dev.tfvars

  terraform-dev:
    name: Dev Environment - Init, Plan, Apply
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Initialize Dev Environment
        run: cd environments/dev && terraform init

      - name: Plan Dev Environment
        run: cd environments/dev && terraform plan -var-file=dev.tfvars

      - name: Apply Dev Environment
        run: cd environments/dev && terraform apply -auto-approve -var-file=dev.tfvars
