aws_region            = "us-east-1"
environment           = "dev"
instance_count        = 2
instance_type         = "t3.micro"
vpc_id                = "vpc-01864e63ac5d0b6c5"                                  # Your default VPC
subnet_ids            = ["subnet-079af9716deaf665a", "subnet-0c2cd654026e6eaf3"] # Dev subnets
key_pair_name         = "linux"                                               # Your SSH key pair
associate_public_ip   = true
ssh_cidr_blocks       = ["122.172.81.53/32"] # Your public IP
http_cidr_blocks      = ["0.0.0.0/0"]
root_volume_type      = "gp3"
root_volume_size      = 20
enable_ebs_encryption = true
enable_monitoring     = true
common_tags = {
  Project     = "TerraformEC2"
  Environment = "dev"
  Terraform   = "true"
}
